W5D1/RedditClone/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :subs
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W5D1/RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W5D1/RedditClone/app/models/cat.rb
class Cat < ApplicationRecord
end

W5D1/RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord

  validates :title, :user_id, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :subs,
    through: :postsubs,
    source: :sub

  has_many :postsubs,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Sub

end

W5D1/RedditClone/app/models/postsub.rb
class Postsub < ApplicationRecord
  validates :post_id, :sub_id, presence: true

  belongs_to :sub
  belongs_to :post


end

W5D1/RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  url         :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text             not null
#

class Sub < ApplicationRecord
  validates :title, :url, :moderator, :description, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :posts,
    through: :postsubs,
    source: :post

  has_many :postsubs


end

W5D1/RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  before_validation :ensure_session_token

  has_many :subs
  has_many :posts

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest= BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user= User.find_by(username: username)
    return nil if user.nil?
    if user.valid_password?(password)
      return user
    else
      return nil
    end
  end

  def reset_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save
    self.session_token
  end



end

W5D1/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def require_current_user
    redirect_to new_session_url unless signed_in?
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def signed_in?
    !!current_user
    # if current_user
    #   return true
    # else
    #   return false
    # end
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end


end

W5D1/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_current_user, except: [:show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
    @post = current_user.posts.find_by(id: params[:id])
    if @post
      # @post = Post.find(params[:id])
      render :edit
    else
      flash[:errors] = ["not your post!"]
      redirect_to posts_url
    end
  end

  def update
    @post = current_user.posts.find_by(id: params[:id])

    if @post.update_attributes(post_params)
      redirect post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_url
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :user_id, sub_ids:[])
  end
end

W5D1/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      sign_in(@user)
      redirect_to "/subs"
    else
      flash[:errors] = ["something"]
      render :new
    end
  end


  def destroy
    sign_out
    render :new
  end
end

W5D1/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_current_user, except: [:index, :show]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def edit
    @sub = Sub.find_by(id: params[:id])

  end

  def update
    @sub = current_user.subs.find_by(id: params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = current_user.subs.find_by(id: params[:id])
    @sub.destroy
    redirect_to subs_url

  end

  def sub_params
    params.require(:sub).permit(:title, :url, :description)
  end

end

W5D1/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user  = User.new
  end

  def create
    @user  = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to "/subs"
      # redirect_to "/subs/#{@sub.id}"
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end


  def user_params
    params.require(:user).permit(:username, :password)
  end

end

W5D1/RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

W5D1/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

W5D1/RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

W5D1/RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/RedditClone/app/views/subs/edit.html.erb
<h1>Edit sub here!</h1>

<%= flash[:errors].join("<br>").html_safe if flash[:errors]%>

<form class="" action="<%=sub_url(@sub)%>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label for="">Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label for="">URL
    <input type="text" name="sub[url]" value="<%= @sub.url %>">
  </label>

  <label for="">Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Edit Sub!">

</form>

W5D1/RedditClone/app/views/subs/index.html.erb
<h1>All Subs:</h1>

<p>
<% Sub.all.each do |sub| %>
  <%= link_to sub.title, sub_url(sub)  %>
  <br>
<% end %>
  <br>
    <br>
      <br>
<%= link_to "Make new sub", new_sub_url  %>

</p>

W5D1/RedditClone/app/views/subs/new.html.erb
<h1>Make a new sub!</h1>

<%= flash[:errors].join("<br>").html_safe if flash[:errors]%>

<form class="" action="<%=subs_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label for="">Title
    <input type="text" name="sub[title]" value="">
  </label>

  <label for="">URL
    <input type="text" name="sub[url]" value="">
  </label>

  <label for="">Description
    <input type="text" name="sub[description]" value="">
  </label>

  <input type="submit" name="" value="Submit">

</form>

W5D1/RedditClone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<% if @sub.moderator == current_user %>
<%= link_to "Edit this Sub", edit_sub_url(@sub) %>
<% end %>

<br>
<%= link_to "Create New Sub", new_sub_url  %>
<br>
<%= link_to "Create New Post", new_post_url  %>





<br>
<br>
<h3>hosted by:<%= @sub.moderator.username %></h3>

W5D1/RedditClone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= flash[:errors].join("<br>").html_safe if flash[:errors]%>

<form class="" action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label for="">Username
    <input type="text" name="user[username]" value="">
  </label>

  <label for="">Password
    <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up">

</form>