W4D2/NinetyNineCats/config/routes.rb
Rails.application.routes.draw do

  resources :cats
  

end

W4D2/NinetyNineCats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  age         :integer          not null
#  sex         :string(1)        not null
#  name        :string           not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord

  COLORS = ["Brown tabby", "Black", "Brown", "Seal point", "Blue point", "Cinnamon", "Marmalade"]
  validates :birth_date, presence: true
  validates :color, presence: true, inclusion: {in: COLORS, message: "Not a valid color"}
  validates :age, presence: true
  validates :sex, presence: true
  validates :name, presence: true
  validates :description, presence: true


  has_many :rental_requests, dependent: :destroy,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest
end

W4D2/NinetyNineCats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("Pending"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date,  presence: true
  validates :status, presence: true, inclusion: { in: ["Pending", "Approved", "Denied"], message: "Invalid status"}
  validate :overlapping_requests

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  private
  def overlapping_requests
    approved_requests = CatRentalRequest.execute(<<-SQL, self.cat_id, self.id)
    SELECT
      cr.*
    FROM
      cat_rental_requests cr
    JOIN cats c ON cr.cat_id = c.id
    WHERE c.id = ? AND cr.id != ? AND cr.status = 'Approved'
    SQL
    unless approved_requests.exists?
      errors[:status] << "Already approved for a rental"
    end
  end

end

W4D2/NinetyNineCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

W4D2/NinetyNineCats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      render :show
    else
      render json: @cat.errors.full_messages, status: 400
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = find_cat
    render :edit
  end

  def show
    @cat = find_cat

    if @cat
      render :show
    else
      render json: "No such cat", status: 400
    end
  end

  def update
    @cat = find_cat
    if @cat.update_attributes(cat_params)
      render :show
    else
      render json: @cat.errors.full_messages, status: 400
    end
  end

  def destroy
    @cat = find_cat
    if @cat
      @cat.destroy
      render :index
    else
      render json: "No such cat exists", status: 404
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :age, :birth_date, :description)
  end

  def find_cat
    Cat.find_by(id: params[:id])

  end
end

W4D2/NinetyNineCats/app/helpers/cats_helper.rb
module CatsHelper
end

W4D2/NinetyNineCats/app/views/cats/_form.html.erb
 <% _action = (cat.id ? cat_url(cat) : cats_url)%>
 <% _verb = (cat.id ? "PATCH" : "POST") %>

<form action="<%=_action%>" method="post">
  <input type="hidden" name="_method" value="<%=_verb%>">

    Name
    <input type="text" name="cat[name]">

  <br>

    Birthdate
    <input type="date" name="cat[birth_date]">

  <br>
    Sex
    <div>
    <input type="radio" name="cat[sex]" value = "M" checked >
    <label for ="M">Male</label>
    <input type="radio" name="cat[sex]" value="F">
   <label for="F">Female</label>
 </div>

 <br>
 Age
  <input type="text" name="cat[age]">

  <br>
  Color
  <select name="cat[color]">
    <option disabled selected>--Select a Color--</option>
  <%Cat::COLORS.each do |color|%>
    <option value = "<%=color%>"> <%=color%> </option>
    <%end%>
  </select>

  <br>
  <p>Enter a short (or long!) description</p>
  <textarea name = "cat[description]" rows="8" cols="20"> </textarea>

  <br>
  <input type = "submit"></input>

</form>

W4D2/NinetyNineCats/app/views/cats/edit.html.erb
<h1> Update a cat's info! </h1>

<%= render 'form', cat: @cat %>

W4D2/NinetyNineCats/app/views/cats/index.html.erb
<h1> All the coolest cats in the world! </h1>

<% @cats.each do |cat| %>
  <%= cat.name %>
  <br>
<% end %>

<%= button_to "Add cat", new_cat_url, method: :get %>

W4D2/NinetyNineCats/app/views/cats/new.html.erb
<h1> Register a new cat! </h1>

<%= render 'form', cat: @cat %>

W4D2/NinetyNineCats/app/views/cats/new_backup.html.erb
<h1> Register a new cat! </h1>



<form action=<%=cats_url%> method="post">
  <input type="hidden" name="_method" value="POST">

    Name
    <input type="text" name="cat[name]">

  <br>

    Birthdate
    <input type="date" name="cat[birth_date]">

  <br>
    Sex
    <div>
    <input type="radio" name="cat[sex]" value = "M" checked>
    <label for ="M">Male</label>
    <input type="radio" name="cat[sex]" value="F">
   <label for="F">Female</label>
 </div>

 <br>
 Age
  <input type="text" name="cat[age]">

  <br>
  Color
  <select name="cat[color]">
    <option disabled selected>--Select a Color--</option>
  <%Cat::COLORS.each do |color|%>
    <option value = "<%=color%>"> <%=color%> </option>
    <%end%>
  </select>

  <br>
  <p>Enter a short (or long!) description</p>
  <textarea name = "cat[description]" rows="8" cols="20"> </textarea>

  <br>
  <input type = "submit"></input>

</form>

W4D2/NinetyNineCats/app/views/cats/show.html.erb
<h1> The Coolest Cat: <%= @cat.name %> </h1>


<h2>Cat Characteristics</h2>




  <body>
  <h3>Description</h3>
  <%= @cat.description %>
  <br>
---------------------------------------------------------

</body>

<br>
<%= button_to "Edit this cat", edit_cat_url(@cat), method: :get%>
<br>
<%= button_to "Delete this cat", cat_url(@cat), method: :delete%>
---------------------------------------------------------
<br>
<section>
<table>
  <tr>
    <th> Name </th>
    <th> Sex </th>
    <th> Color </th>
    <th> Age </th>
    <th> Birth Date </th>
  </tr>
  <tr>
    <td> <%= @cat.name %> </td>
    <td> <%= @cat.sex %> </td>
    <td> <%= @cat.color %> </td>
    <td> <%= @cat.age %> </td>
    <td> <%= @cat.birth_date %> </td>
  </tr>
  <section>

W4D2/NinetyNineCats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <!-- <%#= stylesheet_link_tag    'application', media: 'all' %>
    <%#= javascript_include_tag 'application' %> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>